### ISSUE TITLE
In the macro-synteny viewer, the query chromosome should be grouped with the other chromosomes that have counterparts in the micro-synteny viewer

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#117]
When the "Micro-synteny ordering" option is selected in the macro-synteny viewer, all the chromosomes that are represented in the micro-synteny viewer are floated to the top and given the same ordering as their counterpart in the micro-synteny viewer, except for the query chromosome. Fix this!

**Comment by adf-ncgr** [comment]
not sure this is a really a bug; Alan's example query gene was: glyma.Glyma.08G224600
in this case, although there are other regions of glyma.Chr08 that have synteny to glyma.Chr08,
they are not in the region of the gene, hence glyma.Chr08 only appears as the query track in the microview (and no other glyma.Chr08 microtracks are present); so the macrotrack that contains blocks indicating glyma.Chr08 self-synteny does not appear in the set of tracks that are microsyntenic (although it does get a bold label).

I feel this is appropriate behavior (except perhaps for the emboldening of the macrotrack label, which is minor), though an arguably more appropriate behavior would be to simply allow the macroblocks to appear in the top track of the macroview that represents the query (ie not have glyma.Chr08 represented once without blocks up there and another time with blocks down below). Alan says that is more work than he wanted to tackle now because of the occasional need to resize the track when blocks are overlapping. So, I will back burner this and maybe someday we will revisit as an enhancement...

**Comment by alancleary** [comment]
@adf-ncgr You make a compelling argument. Since the query chromosome is grouped with the other chromosomes in the macro view when it actually has a track in the micro view, I think I can live with the behavior as is. Closing.
