### ISSUE TITLE
Improve GCV landing page at LegumeFederation and LegumeInfo

### ISSUE THREAD

**Issue by ekcannon** [legumeinfo/lis_context_viewer#123]
The current landing pages leave much to be desired, in describing the tool, how to use it, and how to get to it.

Add a link to paper (via its DOI):
https://www.ncbi.nlm.nih.gov/pubmed/29194466

Current help and information should be added or linked:
- Documentation (probably could use updating) :
- https://github.com/legumeinfo/lis_context_viewer/wiki/User-Help
- https://github.com/legumeinfo/lis_context_viewer/wiki/Examples
- the user tour (also probably could use updating)

Improve entry to tool, possibly via a form to set up initial parameters, or a list of clearly described links.

**Comment by adf-ncgr** [comment]
@ekcannon please have a look at the legfed-stage entry page update and see if you think the examples 
(meant to give an example of a query gene from each of the currently federated sites) are a step in the right direction. 

@alancleary, it occurred to me while messing about with the instructions component on the legfed-settings branch that a better solution might be to allow some of this to be done via the config.json, e.g. any of the source servers could have a query gene example (to appear in the placeholder of the box when the source is selected in the dropdown) and also some descriptive text that could be used in making a list of examples (possibly also a concrete URL if some customization to the default params for the example are deemed useful for showing it off to best advantage). At least this would allow sites like the insect genome group in France not to have to change the gene-search code so that the placeholder text wasn't a common bean gene...

**Comment by ekcannon** [comment]
Much better! For one thing, it highlights the federated nature of the tool. The gene search bar at the top is very nice.

It might be helpful to include an annotated static image ("this shows macro synteny", "this shows gene-level synteny", "this is an inversion", "the colors show gene families", ...) so people coming to the GCV for the first time can get a sense for what it is and does.

**Comment by alancleary** [comment]
@adf-ncgr That seems reasonable - the GCV could certainly use more meta programming.

@ekcannon I think such an image would be quite useful. What would be the interplay between it and the interactive help we hope to some day implement? See #32

**Comment by alancleary** [comment]
The changes outlined in the original post have been made in commit 63c5167bca17a1b960348c106ede60f8ddd49259. Some linking and user configuration functionality still needs to be done.

**Comment by alancleary** [comment]
Examples are now being loaded from the config file (commit 35d8673d6fae85e9f5e020b97a59b95c3c4422a4). It would probably be best if someone such as @adf-ncgr reviewed the example images and text, and if someone such as @ekcannon weighed in on whether these commits actually improve the situation this issue was made to address.

**Comment by alancleary** [comment]
The gene search component has been added to the instructions view (commit d01d87af4baee9995272942a03cd53c0d4e6bbe5) and the placeholder text (example gene) is now being loaded from the config file (commit 6b9b986cd7294be5002404c5f26aeb74c7f63fcf).

**Comment by alancleary** [comment]
As of commit afe7280c51728eb98458d803b536b3be534c9b6c, the landing page has been greatly improved via the inclusion of default content and content defined by the user in the config file. This includes a default tour that users can customize as well as the ability for users to add additional, site-specific tours of their own. Closing.
