### ISSUE TITLE
are we making more service calls than we should?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#136]
if I go to (e.g.): 
http://fisher.ncgr.org:50005/lis_context_viewer/#/search/lis/vigun.Vigun03g207900?neighbors=10&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&regexp=&order=distance&sources=lis&bintermediate=10&bmask=10&bmatched=20&alpha=0.85&kappa=10&minsize=5&minsup=2

and watch the alerts, it seems like many of the messages are appearing twice (or getting coalesced into alerts with a count of 2); the browser console for network calls seems to confirm that we're POSTing each service call twice

![image](https://user-images.githubusercontent.com/2009605/38345614-4f9cc52a-384d-11e8-851a-916ec191a15a.png)

I could be misinterpreting but if we are doing twice the work and not getting any extra credit, it would be good to see if you can figure out what's triggering the extra calls. 

I should note that the instance here is my merge of the client-refactor branch into legumeinfo-settings. it's possible I've caused something funky, though it seems unlikely.

**Comment by alancleary** [comment]
It turns out, yes, every request was being made twice. Each time a service made an http observable, it subscribed to the observable before returning it so that subscribers other than the one that called the service could observe it. This had the side effect of an http request being made for each subscriber, as per Angular's HttpClient specification. Since the intent here was to have multiple subscribers observing the _same_ request, this was a bug. Fixed in commit e1c6e2634f93023ca568e1aa95ccfdd9275653af.
