### ISSUE TITLE
set initial widths of horizontal splits at something a little wiser than 50/50

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#167]
offhand not sure where this gets specified but presumably the style here is responsible for the fact that when the search view is set up initially, the micro/macro views are rather cramped while the legends are somewhat awkwardly spacious:
`<div class="split split-horizontal" id="right" style="width: calc(50% - 5px); user-select: none; pointer-events: none;">
`

**Comment by alancleary** [comment]
Before upgrading to Bootstrap 4, the width of these panes was determined by Bootstrap. Now each pane is simply given 50% of the available width, as your code snippet shows. I believe I did this because previously in some cases the content of the legends was be wider than what Bootstrap had given it, which was aesthetically off-putting. So when upgrading Bootstrap I opted to set the pane width to 50% by default in anticipation of some day automatically setting the width to allow just enough space for the contents of the legends. Apparently that day has come!

**Comment by alancleary** [comment]
Also before upgrading to Bootstrap 4, when the user resized the panes, the dimensions would be saved in local storage so whenever they loaded another view, be it search or multi, the saved dimensions would be used, overriding the defaults provided by Bootstrap. Is this functionality we want to replicate now?

**Comment by adf-ncgr** [comment]
I guess it depends on how difficult it is to implement. If easy, seems like a nice touch, but I wouldn't want to waste too much of your time on fiddling with the fine points (unless you feel you need a good fiddle to release pent-up energy or something)

**Comment by alancleary** [comment]
The vertically split panes in the search and multi views are now dynamically resized when their legends' content changes; commit e88222aec6a456d3cee90f08d85a2ee42aae8578.

If we want to pursue the localStorage feature previously mentioned, then we should open a different ticket. Closing this one now.
