### ISSUE TITLE
Multiple broadcasts when selecting a gene

### ISSUE THREAD

**Issue by svengato** [legumeinfo/lis_context_viewer#191]
When you mouseover a triangle representing a gene in the Micro-Synteny panel, sometimes it takes a while for that gene's label to display (from a user interface point of view, it feels like you have not placed the cursor in exactly the right spot). In such cases, Broadcast Channel repeatedly posts the same sequence of **select**-**deselect**-**deselect** messages until "you hit the spot" and the label appears, along with the final **select** message.

**Comment by adf-ncgr** [comment]
I wonder if this is at all related to the irritating flicker behavior that is sometimes experienced when mousing over (or nearly over) an element? as if the highlighting shifts the coordinate system slightly so that the mouse is no longer over, which reshifts and puts the mouse back, etc. Not sure it is actually shifting, just gives the impression that could be the cause of the oscillating selection.

**Comment by alancleary** [comment]
Ah, yes. I've known about this bug for a while. As you've described @svengato, mousing over a gene glyph causes a label to appear. If the label appears under the cursor, it triggers a mouseout event to be triggered, and so the label disappears, causing a mouseover event to be triggered, and so on. This cycle continues until you move the mouse so that it's not over where the label will appear.

I haven't fixed the problem because I actually intend to replace the labels integrated into the different GCV visualizations with Bootstrap tooltips (see Issue #25). It seems the time has finally come for it to be a priority...

**Comment by alancleary** [comment]
Commit 0aa544c384df3d12bbdb40a442caf394653ea276 replaced the D3 based tooltips in the micro-synteny viewer with Tippy.js tooltips. This has fixed the behavior described in my previous comment.
