### ISSUE TITLE
duplicate key value violates unique constraint "cvterm_c2"

### ISSUE THREAD

**Issue by Yonkers** [legumeinfo/lis_context_viewer#213]
server load script error, using chado v1.31, actually I use [erasche/chado](https://hub.docker.com/r/erasche/chado)

branch: mster

```
DBD::Pg::db do failed: ERROR:  duplicate key value violates unique constraint "cvterm_c2"
DETAIL:  Key (dbxref_id)=(1) already exists. at scripts/perl/gmod_gene_families.pl line 171.
```

**Comment by adf-ncgr** [comment]
Hi, thanks for pointing this out. I guess this must be due to something in erasche/chado having already loaded a cvterm that references the so-called "local:null" dbxref which I had mistakenly believed would be non-problematic to use for ontology terms we're defining for the purposes of the app alone and without implying any other "semantic baggage". If this were a regular "null" I think it would be OK to have duplicated values despite the uniqueness constraint; this is an area in which chado convention seems to be a little problematic (or maybe I just don't understand the intent of the terms that are like nulls, but actual rows). In any case,  I guess the thing to do would be to define our own cv for the app and avoid such collisions altogether. Not difficult in principle, but I need to give some thought to how to address backward compatibility. In the meantime, you might want to just use a workaround if you are just exploring; I think you could just tweak the script gmod_gene_families.pl to replace all instances of "local:null" with "local:gcv_null" (or whatever) and
things should work just fine.

let us know if that doesn't serve your immediate purposes.

**Comment by Yonkers** [comment]
the script  `gmod_gene_families.pl` add two row ( `gene family` and `family representative`) to the table `cvterm`, and these two row have the same value of `dbxref_id`, but the column `dbxref_id` in table `cvterm` is unique of each row, that's the problem, `dbxref_id` can't be the same,  I replaced "local:null" to "local:gcv_null", this problem still exist:
```
DBD::Pg::db do failed: ERROR:  duplicate key value violates unique constraint "cvterm_c2"
DETAIL:  Key (dbxref_id)=(113674) already exists. at scripts/perl/gmod_gene_families.pl line 181.
```
may `gene family` and `family representative` have different `dbxref_id`.

**Comment by adf-ncgr** [comment]
yes, you're right; I was a bit confused since I've never run into this problem myself, but I think I know why that is. also, I didn't look at the code closely enough before responding. in any case, it looks like I broke it in this commit: bc3e7f27e4878f93f5ac414ccbd0bdd061333185 and I should probably just revert to using that strategy- I think I was also wrong about there being potential issues with backward compatibility, at least with respect to how dbxref is handled there, as I am pretty sure this is only being done to satisfy chado constraints and is no where used by the application code. will try to get a fix in soon.

**Comment by adf-ncgr** [comment]
sorry for being slow to get back to this; let me know if that doesn't work on your end, I did a little minimal testing against https://hub.docker.com/r/erasche/chado and it seemed to work as expected
