### ISSUE TITLE
Some genes with families are being labeled as orphans after their gene data is loaded

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#268]
Take this view for example:

/gene;lis=lotja.Lj0g3v0166889,cicar.Ca_05015_gene,glyma.Glyma.06G088000,glyma.Glyma.04G086500,araip.Araip.Z4RG3,vigra.Vradi05g08580,araip.Araip.0T13B,medtr.Medtr3g110360,cajca.C.cajan_36467_gene,phavu.Phvul.009G111700,aradu.Aradu.M206V?algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=50&bmatched=20&bintermediate=10&bmask=10&linkage=average&neighbors=25&matched=4&intermediate=5&sources=lis&bregexp=&border=chromosome&regexp=&order=distance

Notice how before gene data is loaded for the result tracks the lupal.Lalb_Chr08 track clearly has colors for its gene families and its non-orphan families have been used to align it to the cluster consensus. After the gene data is loaded, the track's alignment remains but all its genes are drawn as orphans. This is a bug!

**Comment by adf-ncgr** [comment]
Hi-
just saw this. If you are getting results that include "lupal" you must be working on either lis-dev or lis-stage. I am not %100 confident that lupal might not have some weird data issues. I've got my services talking to a db that doesn't include it, so not sure I can reproduce/help assess whether the "bug" could be data-driven rather than code driven. The loading of this genome is also somewhat different between lis-dev and lis-stage; I'd expect the latter to be more likely to behave better, but you never know. we can discuss further if it might help

**Comment by alancleary** [comment]
@adf-ncgr lupal seems to be the only genome affected in the example I provided. Let's chalk it up to "data issues" for now and icebox the issue until it rears it head or becomes stale.

**Comment by adf-ncgr** [comment]
sounds good- it could also be that I loaded it into the db after your server was started and something's missing from a cache.

**Comment by alancleary** [comment]
I use the Django dev server while developing so I suspect it's not a caching issue.

**Comment by adf-ncgr** [comment]
sure, but isn't there some caching of db query results that goes on when you startup the server? That's what I was referring to...

**Comment by alancleary** [comment]
I only run the server when I'm actively working on GCV, so the cache is cleared at least daily. I just restarted the server, which flushed the cache, and confirmed the lupal gene families are sting unasigned after the gene data has been loaded.

**Comment by alancleary** [comment]
I've confirmed that this is only an issue in the dev environment and is thus a data error. Closing.
