### ISSUE TITLE
GCV: Help

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#32]
<p>The Genome Context Viewer Help needs help... Remove the blue help boxes and make the Help button toggle Help mode. When in help mode, whatever element the user clicks on will pull them into that element's step in the Bootstrap tour. Such "hooks" into the tour should cause the next button to be suppressed.</p>
<i>[LEGUME-690] created by alancleary</i>

**Comment by alancleary** [comment]
Commit 13cffcf8bb8605911eb5358ee6e7415c7533a9d5 added a help dropdown to the main navbar with links to all available help resources. Commit 1cb2883f9eb09b16fe375f4b34edf3ef9405af62 added a pipeline component which is now used in several places throughout the app to convey what is happening.

Though these commits don't accomplish specifically what this issue asked for, they drastically improve the "help" situation and add clarity into how the GCV actually works. Furthermore, the tour functionality has been effectively removed from the new release of the GCV and since its fate is uncertain (and outside the scope of this issue) I deem this issue complete. Closing.
