### ISSUE TITLE
Macro-synteny viewport drag-and-drop

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#330]
I thought there was an issue for this but I couldn't find it...

The drag-and-drop functionality of the macro-synteny viewport was broken with the GCV version 2 release. Previously, dragging the viewport highlighting what part of the macro-synteny viewer corresponded to the current micro-synteny view to a new location would cause a new micro-synteny view to be loaded with the newly highlighted segment as the query track. This would simply figure out what the gene at the center of the newly highlighted region would be and the new query track would be built with that gene and the number of neighbors would be the same as in the previous micro-synteny view. However, I've just reimplemented this functionality (not committed yet) where a new neighbor value is also returned by the service that finds the center gene. Since genes are not uniformly distributed across chromosomes, this may be different than the previous neighbors value. @adf-ncgr what do you think; should the number of neighbors for the newly highlighted region be carried over from the previous microi-synteny view or should the new value from the region service be used?

Either way, the purpose of this ticket is to document the reimplementation of this functionality.

**Comment by alancleary** [comment]
Region searching via drag-and-drop of the macro-synteny viewport was reimplemented in commit b261d44ff67bc0425ff497ec5aa4fdd5afe1dd3f. This is different from the previous implementation in that the number of neighbors in the micro-synteny query track computed from the viewport drag-and-drop is determined from the extent of the region rather than using the previous context's neighbors parameter value.

I'll leave this ticket open in case @adf-ncgr or someone else wants to weigh in on this inconsistency.

**Comment by adf-ncgr** [comment]
I weighed in on this in an email thread, but for the sake of more proper etiquette, transferring thoughts here...

if we're going to make the macro view basically do a region search rather than respecting the neighbors setting, how hard would it be to convert the "modality" of the interaction so they can just brush an arbitrarily-sized region instead of having the fixed-size window that they can drag into a new location? This seems more flexible,
and possibly somewhat more intuitive- or at least it would better facilitate navigation by "this region looks interesting by its block structure", since you wouldn't have to do a post hoc resize to accommodate actual block extent after moving a window (which is actually something I do frequently)

it would also be good to have a similar brush-to-define-region for the microview. In that case, it might not be used for
altering the region (although one could imagine using it as a "zoom in"), but there are some use cases that could be enabled by having a handy way of defining regions (e.g. a recent discussion with a prospective new pangenome user indicate interest in it as a selection mechanism for sequence retrieval; I've done some things like this before at the level of "genes" or "tracks" and have wanted to be able to do it on intergenic regions, or more arbitrarily selected "from this gene to that gene and all of the corresponding regions in the other tracks" sorts of things).

**Comment by alancleary** [comment]
@adf-ncgr I don't think these sorts of brush functionalities would be too difficult to implement, but I don't think it would necessarily be trivial either. Something worth considering is consistency of brushing behavior across visualizations. Having brushing plots cause a zoom, brushing micro-synteny trigger a download, and brushing macro-synteny load a context could be confusing to the user. That's not to say we shouldn't implement these features, but perhaps, for the sake of consistency, brushing any visualization should cause a popup widget to appear with a list of one or more visualization-specific functionalities that can be performed on that visualization via a brushing.

Whatever we decide to do, this should probably be wrapped into a visualization epic. As you may recall from the version 2 / golden layout epics, all the auto-resizing code in the visualizations was deprecated because it wasn't playing nice with golden layout and it was making the visualization code a mess since it affected so many elements. This code still needs to be removed from the visualizations and I would definitely like to do that before trying to add new functionality like brushing.

**Comment by adf-ncgr** [comment]
Yes, I think if there are multiple possible options to invoke after a "region select" then a popup makes a lot of sense (and will get me feeling nostalgic for the good old days of "dynamic discovery" in ISYS). It might be debatable whether a pop-up with one option is a good idea (although I suppose the implicit "do-nothing, I didn't really mean it" option could be justification for the added click if your UX consistency argument isn't sufficient). Maybe just treating regions as another sort of entity (like genes) that get details components with internal and external (linkout) options when "selected" by brushing is the way to go? We actually do have a region linkout service that Sven added to the legfed site, this would be a good excuse to leverage it.

**Comment by alancleary** [comment]
I think the scope of this issue has been addressed so I'm going to close it. Feel free to continue the discussion of new viewer features in the visualization epic, #337.
