### ISSUE TITLE
GCV: Visualization workers

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#35]
<p>The various visualizations are currently blocking the interpret when being drawn, effectively freezing the UI until they are done. This can be remedied by using Web Workers when drawing.</p>
<i>[LEGUME-683] created by alancleary</i>

**Comment by alancleary** [comment]
[Apparently](https://stackoverflow.com/a/45050754) the problem is that we're drawing our visualizations to SVG, which means D3 is adding DOM elements, calculating the image, and painting all in the main thread. Not only is there no way to move all this out of the main thread, but the massive number of DOM elements we're drawing makes the rest of the page sluggish.

The remedy seems to be switching from SVG to canvas, which uses less DOM elements and actually utilizes the GPU. Canvas is supported in D3 v4, so that's an excuse to upgrade, which we already have a ticket for: #71
