### ISSUE TITLE
Chado loading perl scripts

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#58]
The perl scripts used to load data into the modified Chado database for consumption by the Genome Context Viewer reside in https://github.com/ncgr/lis_gene_families. Add these scripts to this repository.

**Comment by alancleary** [comment]
Added pearl and bash scripts from [lis_gene_families repo](https://github.com/ncgr/lis_gene_families) in commit e144a174a837383f0ae16e3f6041f1c2e455e43e to branch JCVI. Not sure which scripts are actually relevant here so they need review.

**Comment by adf-ncgr** [comment]
just glanced over the scripts in the lis_gene_families repository; after this trip down memory lane I more fully appreciate the comment @alancleary made about having to swallow his pride when serving as a summer intern in order to get us to where we are today! I think the only scripts that might want to be adopted into this repos are:
gmod_gene_ordering.pl (I still use this one)

gmod_gene_families.pl (this one is debatable; it uses phylotree to determine gene-family assignments, but since developing a tree-independent way of doing this, I am not sure if we need this; will probably leave in its current repository and not introduce trees into this one for now; the same applies to the tree and msa loading scripts in the older repository; they are in fact still used but not appropriate for this repository)

hopefully we will never again have cause to remember the existence of the gmod_gff3_prepreprocessor.pl script !

I may have a couple of other little scriptlets that represent my current way of doing things; likely still embarrassing to anyone who still has pride, but we'll continue to evolve...

**Comment by adf-ncgr** [comment]
fixed in 46e6ee2
