### ISSUE TITLE
Span based search

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/lis_context_viewer#61]
In the search view, the user should be able to provide a genomic interval for a chromosome, perhaps on the current query chromosome, for which to perform a new search. Ideally this would just be a matter of expanding the UI to allow the user to interact with the existing "Nearest Gene" service.

**Comment by adf-ncgr** [comment]
we might want to consider making this independent of the nearest gene service; I could imagine, for example, selecting a macrosynteny block and have that determine the span to be searched. And although
getting ridiculously long spans is a potential concern, it would certainly be simple to form a query track with a span and nothing else. perhaps numNeighbors could be used if present and if not present then the entire span would be used. not sure a good idea, just thinking that in many contexts when a span is supplied, the user will get confused if a magical transform to a subspan is effected for their comfort and safety (I suppose they could be warned)

**Comment by adf-ncgr** [comment]
another note to future selves (mostly future Alan) when it comes to implementing this one; there seems to be no reason in principle why this couldn't be extended to a multispan mode so that we could complete our set of options with pleasing symmetry:
1) entering a gene name and finding syntenic contexts
2) entering a set of gene names and getting the aligned syntenic groupings among them
3) entering a single span and finding syntenic contexts
4) entering a set of spans and getting the aligned syntenic subgroupings among them

One could imagine a set of spans being determined by something like a query (not the responsibility of GCV) for the set of regions associated with a trait across a number of species (ie QTLs or GWAS-defined areas).

Also note that 4) would be a nice way of getting from search mode into multi-alignment mode; although possible now using the families trick it suffers from the problem that any track having a deletion of the selected gene family will be left behind....

**Comment by adf-ncgr** [comment]
@sammyjava can you remind me of your use case for this so we can take into account when setting priorities for our next round of development?

**Comment by sammyjava** [comment]
Just the CSw8 example: I've got a genomic range from QTL markers, and I'd like to simply enter the range between the first and last to get the corresponding range on the context viewer.

**Comment by adf-ncgr** [comment]
FWIW, Nevin Young also asked for this functionality...

**Comment by adf-ncgr** [comment]
And nearly a year later, Nevin still yearns for it; let's make it happen before Ardmore!

**Comment by alancleary** [comment]
Implemented a span-to-context service in commit: f097efb6a9797652ce8d482a19deee4728b0cebb

Implemented URL span-based searching from the client in commit: c8c900b65a8178f77389cd62941f6890450b298c

Turn a span on a chromosome into a GCV search via the client URL as follows: /search/<source>/<chromosome>/<span>. For example: /search/lis/phavu.Chr02/13142457-13496658

**Comment by alancleary** [comment]
Commits 1946d808bc0f854daf6cb5d525a1c10d8621f3b0 and 1477d0b3d0d4cde7b00ccc3767f254820164951e added span-based search support to the search widget in the client.

**Comment by alancleary** [comment]
Commit a4b6c6d26be314d0e287c944de496229a5692352 updated the Search component to alert the user when a span request is being processed and when it fails. The SpanSearch guard now immediately directs users to the search view and doesn't redirect if the span request fails.

**Comment by alancleary** [comment]
Added support for spans defined using the ".." syntax in commit 67ed8ae46bb0e347b452296df261cca67026f496.
