### ISSUE TITLE
does pan-view preserve gene family color assignments in local storage?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#76]
I've always been a little fuzzy on the details of how this is implemented for the search view, but I seem to have convinced myself that the pan view does not behave the same way, and also the
search view colors are not preserved with you flip a set of genes into pan-view from that context; For example starting in this search view:
http://localhost:3000/#/search/lis/glyma.Glyma.13G367400?neighbors=10&sources=lis&matched=4&intermediate=5&algorithm=repeat&match=10&mismatch=-1&gap=-1&score=30&threshold=25&regexp=&order=chromosome
 for me the focus gene is red, and not terribly well represented in the tracks below but the pale green gene just to the left is present in almost all tracks. clicking the pale green gene family (phytozome_10_2.59036226) and then selecting the pan-view option, the phytozome_10_2.59036226 family (now the focus) is red, with a pale green gene set to its left. Similarly, if now in the pan-view I select the family (phytozome_10_2.59297604) corresponding to a well-conserved black column to the right, if I avoid the behavior related to #16 by opening in a new tab the same family phytozome_10_2.59297604 now the focus appears as red. Obviously, a poor aesthetically driven user like myself gets very mixed up when the same genes get a radical makeover as the view changes...

**Comment by alancleary** [comment]
The local storage backup of the micro-synteny colors was not reimpemented when we moved from Angular 1 to 2. We should probably do this at some point.

For now, it seems the entire app is being reloaded when going from the search view to the pan view, and vice versa. This is likely due to how the hyperlinks between views are coded. Updating them to only target the Angular specific fragment that comes after the hash should fix the problem, making the colors consistent between consecutive views.

**Comment by adf-ncgr** [comment]
NB: I think I may have already done the hyperlink change you suggested, probably on the master branch. I may have only done it in one direction though (e.g. pan -> search and not search -> pan or vice-versa).

**Comment by alancleary** [comment]
Looks like you did. I just updated the link in the family detail component to be correct as well: 6de753987bdec539932c780abe3cff49cc9a9710. This seems to have made the colors consistent when switching between the pan and search views.

Do we want to close the issue or add local storage so that colors are consistent between sessions?

**Comment by adf-ncgr** [comment]
I'll think about it (in conjunction with some more testing); 
IIRC, the main motivation for preserving color assignments was to help preserve sanity after we had introduced "scrolling", but it seems like that would be within-session,
so I'm not entirely sure. There may be a weak motivation to do it for other reasons (e.g. preserving sanity when making slides with screenshots) but nothing that would be too pressing for the moment.

**Comment by adf-ncgr** [comment]
I guess another reason to do this is to facilitate multi-tab/window usages/abusages, the latter of which I seem to be constantly guilty of. How hard is it to reimplement? Not sure I want to make it a priority, but I think I've convinced myself it's a very-nice-to-have.

**Comment by alancleary** [comment]
Local storage functionality added in commit a2d42692ffaf210fa4070a0be47b8f9ff78848d5
