### ISSUE TITLE
renaming of files, directories, components which preserve the memory of "basic" view

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/lis_context_viewer#96]
it's liable to get confusing at some point.

**Comment by alancleary** [comment]
Done in commits bdc8bd974a34204b225902b4238dfcdcd645fbf9, fe6fa209a96162f4d2da596fffcca1b467a68c3f, ff75930b1cfc0ada2ace0a731ee8dd7d0c03069d, and d30a311d6968aa025d8b218e64c9f3a4d3db6d8b.

The server and services API still use "basic", rather than "multi". This change will be made in version 1.1 of the API, though "basic" will still be supported until 1.2 for backwards compatibility.
